### PR TITLE
fix: don't pass null to `strtoupper` as its deprecated in PHP 8.1

### PR DESCRIPTION
**Pull request by G-Rath**
It would be awesome if this could be landed into v1.x as it looks like the only stopper to moving to PHP 8.1 for us, and I don't know if/when parent packages will upgrade to use v2 of this library 🙏

### CODE REVIEW

**Comment by muskie9** [comment]
@G-Rath thanks for putting in the pull request! Since this PR is against master, I just want to confirm what branch you're referring to for v1. We experienced issues with a change of package requirements causing the new major version.

We're also interested in knowing what other packages may be requiring ours so we can possibly patch and test those easing upgrades to the new major version of this module.

**Comment by G-Rath** [comment]
@muskie9 I hadn't realised there was a v1 branch until after I made the PR 😅 happy to change this to v1 if you're happy to merge

**Comment by muskie9** [comment]
@G-Rath after reviewing this further, the 2.0 branch is mostly 8.1 compatible with additional requirement changes we found with our 8.1 testing. 2.0 definitely has the deprecation warning so I think this change makes sense against the 2.0 branch. This deprecation may be the only aspect that we didn't catch at this point.

We did just have this come up so I'll be patching for 2.0 if you'd like PR against the 1.3 branch without the two additional commits from the 2.0 branch we can merge that change in.

**Comment by G-Rath** [comment]
@muskie9 I'm not sure I entirely follow, but so long as we end up with a v1.3.1 version getting published with this change then I'll be happy 😄

**Comment by muskie9** [comment]
@G-Rath when you started your branch was it from 2.0 or 1.3?

There are 2.0 branch changes in the PR commits that would be ported back to 1.3 branch which isn't something that can happen (semvar and what not). The PR would need to start from 1.3 in order to be merged into 1.3 if that makes sense. We could then do a new release from that branch.

**Comment by G-Rath** [comment]
@muskie9 it was started from the default branch (`master`) - I'm wondering if it might better if you handled doing the actual PRs for both versions, since it sounds like you already know how everything should be laid out and the code change should be just this one line so easy to apply in either case.

**Comment by muskie9** [comment]
Sounds good @G-Rath, I'll be patching 2.0 branch shortly (this branch is currently default), then I'll apply to 1.3 and both will get a new release.

**Comment by muskie9** [comment]
New release with fix from @G-Rath: https://github.com/dynamic/silverstripe-geocoder/releases/tag/1.3.1

**Pull request closed without merging**
